server:
  port: 7777
spring:
  application:
    name: spring-cloud-config-client
eureka:
  instance:
    preferIpAddress: true
    #这样写eureka服务注册中心会显示本机ip+端口号
    instanceId: 192.168.24.104:7777
    #这样写eureka服务注册中心会显示项目名和端口号
    #instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://ultrazuul:ultrazuulSecret@192.168.24.104:8070/eureka/  #注册中心地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
name: 9991112

logging:
  level: 
   root: info

spring:
 datasource:
   username: msa_10
   password: AnH9WpfGkRHAmEhMJR9YRTDqVp45MAPjj
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://192.168.120.190:3306/msa_10?useUnicode=true&characterEncoding=UTF-8
   initialize: false
