server:
  port: 7777
spring:
  application:
    name: spring-cloud-config-client
eureka:
  instance:
    preferIpAddress: true
    #这样写eureka服务注册中心会显示本机ip+端口号
    instanceId: 192.168.24.104:7777
    #这样写eureka服务注册中心会显示项目名和端口号
    #instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://ultrazuul:ultrazuulSecret@192.168.24.104:8070/eureka/  #注册中心地址

management:
  security:
   enabled: false
  endpoints:
   web:
    exposure:
     include: bus-refresh
name: 12345
